/*
 * Copyright 2015-2025 Ritense BV, the Netherlands.
 *
 * Licensed under EUPL, Version 1.2 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {PluginSpecification} from '@valtimo/plugin';
import {ROTTERDAM_ORACLE_EBS_PLUGIN_LOGO_BASE64} from './assets';
import {ConfigurationComponent} from "./components/configuration/configuration.component";
import {JournaalpostOpvoerenComponent} from "./components/journaalpost-opvoeren/journaalpost-opvoeren.component";
import {VerkoopfactuurOpvoerenComponent} from "./components/verkoopfactuur-opvoeren/verkoopfactuur-opvoeren.component";

const rotterdamOracleEbsPluginSpecification: PluginSpecification = {
    pluginId: 'rotterdam-oracle-ebs',
    pluginConfigurationComponent: ConfigurationComponent,
    pluginLogoBase64: ROTTERDAM_ORACLE_EBS_PLUGIN_LOGO_BASE64,
    functionConfigurationComponents: {
        'journaalpost-opvoeren': JournaalpostOpvoerenComponent,
        'verkoopfactuur-opvoeren': VerkoopfactuurOpvoerenComponent,
    },
    pluginTranslations: {
        nl: {
            title: 'Gemeente Rotterdam: Oracle E-Business Suite koppeling',
            description: 'Oracle E-Business Suite plugin voor o.a. het Opvoeren van een Journaalpost',
            'journaalpost-opvoeren': 'Journaalpost opvoeren',
            'verkoopfactuur-opvoeren': 'Verkoopfactuur opvoeren',
            'configuration.title': 'Configuratienaam',
            'configuration.title.tooltip': 'De naam van de huidige plugin-configuratie. Onder deze naam kan de configuratie in de rest van de applicatie teruggevonden worden.',
            'configuration.title.placeholder': 'Gemeente Rotterdam Oracle EBS Plugin',
            'configuration.baseUrl': 'ESB Url',
            'configuration.baseUrl.tooltip': 'De URL van de Gemeente Rotterdam (Opentunnel) ESB',
            'configuration.mTlsSslContextConfiguration': 'mTLS SSL Context Configuratie',
            'configuration.mTlsSslContextConfiguration.tooltip': 'Selecteer de juiste mTLS SSL Context configuratie die gebruikt moet worden voor authenticatie met de ESB.',
            'journaalpost.procesCode': 'Proces code',
            'journaalpost.procesCode.tooltip': 'Vul hier de process code in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'journaalpost.referentieNummer': 'Referentienummer',
            'journaalpost.referentieNummer.tooltip': 'Vul hier het referentienummer in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'journaalpost.sleutel': 'Sleutel',
            'journaalpost.sleutel.tooltip': 'Vul hier de sleutel in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'journaalpost.boekdatumTijd': 'Boekdatum',
            'journaalpost.boekdatumTijd.tooltip': 'Vul hier de boekdatum in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'journaalpost.categorie': 'Categorie',
            'journaalpost.categorie.tooltip': 'Vul hier de categorie in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'journaalpost.saldoSoort': 'Saldosoort',
            'journaalpost.saldoSoort.tooltip': 'Selecteer de saldo soort',
            'journaalpost.saldoSoort.placeholder': 'Maak een keuze',
            'journaalpost.omschrijving': 'Omschrijving',
            'journaalpost.omschrijving.tooltip': 'Vul hier de omschrijving in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'journaalpost.boekjaar': 'Boekjaar',
            'journaalpost.boekjaar.tooltip': 'Vul hier het boekjaar in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'journaalpost.boekperiode': 'Boekperiode',
            'journaalpost.boekperiode.tooltip': 'Vul hier de boekperiode in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'journaalpost.regels': 'Regels',
            'journaalpost.regels.tooltip': 'Voeg minimaal 1 journaalpost regel toe.',
            'journaalpost.regel.toevoegen': 'Regel toevoegen',
            'journaalpost.regel.verwijderen': 'Regel verwijderen',
            'journaalpost.regel.grootboekSleutel': 'Grootboek sleutel',
            'journaalpost.regel.boekingType': 'Boekingtype',
            'journaalpost.regel.boekingType.placeholder': 'Maak een keuze',
            'journaalpost.regel.omschrijving': 'Omschrijving',
            'journaalpost.regel.bedrag': 'Bedrag',
            'verkoopfactuur.procesCode': 'Proces code',
            'verkoopfactuur.procesCode.tooltip': 'Vul hier de process code in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.referentieNummer': 'Referentienummer',
            'verkoopfactuur.referentieNummer.tooltip': 'Vul hier het referentienummer in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.factuurKlasse': 'Factuur klasse',
            'verkoopfactuur.factuurKlasse.tooltip': 'Selecteer de factuur klasse',
            'verkoopfactuur.factuurKlassePlaceholder': 'Maak een keuze',
            'verkoopfactuur.inkoopOrderReferentie': 'Inkoop Order Referentie',
            'verkoopfactuur.inkoopOrderReferentie.tooltip': 'Vul hier de inkoop order referentie in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.natuurlijkPersoonAchternaam': 'Achternaam',
            'verkoopfactuur.natuurlijkPersoonAchternaam.tooltip': 'Vul hier de achternaam van de natuurlijke persoon in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.natuurlijkPersoonVoornamen': 'Voornamen',
            'verkoopfactuur.natuurlijkPersoonVoornamen.tooltip': 'Vul hier de voornaam/voornamen van de natuurlijke persoon in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.nietNatuurlijkPersoonStatutaireNaam': 'Statutaire naam',
            'verkoopfactuur.nietNatuurlijkPersoonStatutaireNaam.tooltip': 'Vul hier de statutaire naam van de niet natuurlijke persoon in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.regels': 'Regels',
            'verkoopfactuur.regels.tooltip': 'Voeg minimaal 1 factuur regel toe.',
            'verkoopfactuur.regel.toevoegen': 'Regel toevoegen',
            'verkoopfactuur.regel.verwijderen': 'Regel verwijderen',
            'verkoopfactuur.regel.hoeveelheid': 'Hoeveelheid',
            'verkoopfactuur.regel.tarief': 'Tarief',
            'verkoopfactuur.regel.btwPercentage': 'BTW pPercentage',
            'verkoopfactuur.regel.grootboekSleutel': 'Grootboek sleutel',
            'verkoopfactuur.regel.omschrijving': 'Omschrijving'
        },
        en: {
            title: 'Municipality of Rotterdam: Oracle E-Business Suite connection',
            description: 'Oracle E-Business Suite plugin for, among other things, entering a journal entry',
            'journaalpost-opvoeren': 'Enter journal entry',
            'verkoopfactuur-opvoeren': 'Enter sales invoice',
            'configuration.title': 'Configuration name',
            'configuration.title.tooltip': 'The name of the current plugin configuration. This name can be used to find the configuration throughout the application.',
            'configuration.title.placeholder': 'Gemeente Rotterdam Oracle EBS Plugin',
            'configuration.baseUrl': 'ESB URL',
            'configuration.baseUrl.tooltip': 'The URL of the Gemeente Rotterdam (Opentunnel) ESB',
            'configuration.mTlsSslContextConfiguration': 'mTLS SSL Context Configuration',
            'configuration.mTlsSslContextConfiguration.tooltip': 'Select the correct mTLS SSL Context configuration to be used for authentication with the ESB.',
            'journaalpost.procesCode': 'Process code',
            'journaalpost.procesCode.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'journaalpost.referentieNummer': 'Reference number',
            'journaalpost.referentieNummer.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'journaalpost.sleutel': 'Key',
            'journaalpost.sleutel.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'journaalpost.boekdatumTijd': 'Booking date',
            'journaalpost.boekdatumTijd.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'journaalpost.categorie': 'Category',
            'journaalpost.categorie.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'journaalpost.saldoSoort': 'Balance type',
            'journaalpost.saldoSoort.tooltip': 'Select the balance type',
            'journaalpost.saldoSoort.placeholder': 'Make a choice',
            'journaalpost.omschrijving': 'Description',
            'journaalpost.omschrijving.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'journaalpost.boekjaar': 'Fiscal year',
            'journaalpost.boekjaar.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'journaalpost.boekperiode': 'Accounting period',
            'journaalpost.boekperiode.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'journaalpost.regels': 'Entries',
            'journaalpost.regels.tooltip': 'Add minimal 1 journal entry',
            'journaalpost.regel.toevoegen': 'Add entry',
            'journaalpost.regel.verwijderen': 'Remove entry',
            'journaalpost.regel.grootboekSleutel': 'General ledger key',
            'journaalpost.regel.boekingType': 'Booking type',
            'journaalpost.regel.boekingType.placeholder': 'Make a choice',
            'journaalpost.regel.omschrijving': 'Description',
            'journaalpost.regel.bedrag': 'Amount',
            'verkoopfactuur.procesCode': 'Process code',
            'verkoopfactuur.procesCode.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.referentieNummer': 'Reference number',
            'verkoopfactuur.referentieNummer.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.factuurKlasse': 'Invoice class',
            'verkoopfactuur.factuurKlasse.tooltip': 'Select the invoice class',
            'verkoopfactuur.factuurKlassePlaceholder': 'Make a choice',
            'verkoopfactuur.inkoopOrderReferentie': 'Purchase order reference',
            'verkoopfactuur.inkoopOrderReferentie.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.natuurlijkPersoonAchternaam': 'Last name',
            'verkoopfactuur.natuurlijkPersoonAchternaam.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.natuurlijkPersoonVoornamen': 'First names',
            'verkoopfactuur.natuurlijkPersoonVoornamen.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.nietNatuurlijkPersoonStatutaireNaam': 'Legal name',
            'verkoopfactuur.nietNatuurlijkPersoonStatutaireNaam.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.regels': 'Entries',
            'verkoopfactuur.regels.tooltip': 'Add minimal 1 sales invoice entry',
            'verkoopfactuur.regel.toevoegen': 'Add entry',
            'verkoopfactuur.regel.verwijderen': 'Remove entry',
            'verkoopfactuur.regel.hoeveelheid': 'Quantity',
            'verkoopfactuur.regel.tarief': 'Rate',
            'verkoopfactuur.regel.btwPercentage': 'VAT percentage',
            'verkoopfactuur.regel.grootboekSleutel': 'General ledger key',
            'verkoopfactuur.regel.omschrijving': 'Description'
        },
        de: {
            title: 'Gemeinde Rotterdam: Oracle E-Business Suite-Anbindung',
            description: 'Oracle E-Business Suite Plugin, u.a. zur Erfassung eines Journaleintrags',
            'journaalpost-opvoeren': 'Journalbuchung erfassen',
            'verkoopfactuur-opvoeren': 'Verkaufsrechnung erfassen',
            'configuration.title': 'Konfigurationsname',
            'configuration.title.tooltip': 'Der Name der aktuellen Plugin-Konfiguration. Unter diesem Namen kann die Konfiguration im Rest der Anwendung gefunden werden.',
            'configuration.title.placeholder': 'Gemeente Rotterdam Oracle EBS Plugin',
            'configuration.baseUrl': 'ESB-URL',
            'configuration.baseUrl.tooltip': 'Die URL des Gemeente Rotterdam (Opentunnel) ESB',
            'configuration.mTlsSslContextConfiguration': 'mTLS SSL-Kontextkonfiguration',
            'configuration.mTlsSslContextConfiguration.tooltip': 'Wählen Sie die richtige mTLS-SSL-Kontextkonfiguration aus, die für die Authentifizierung mit dem ESB verwendet werden soll.',
            'journaalpost.procesCode': 'Prozesscode',
            'journaalpost.procesCode.tooltip': 'Dies kann ein fester Wert sein, aber auch einer der Valtimo-Wertauflöser (case:, doc: oder pv:).',
            'journaalpost.referentieNummer': 'Referenznummer',
            'journaalpost.referentieNummer.tooltip': 'Dies kann ein fester Wert sein, aber auch einer der Valtimo-Wertauflöser (case:, doc: oder pv:).',
            'journaalpost.sleutel': 'Schlüssel',
            'journaalpost.sleutel.tooltip': 'Dies kann ein fester Wert sein, aber auch einer der Valtimo-Wertauflöser (case:, doc: oder pv:).',
            'journaalpost.boekdatumTijd': 'Buchungsdatum',
            'journaalpost.boekdatumTijd.tooltip': 'Dies kann ein fester Wert sein, aber auch einer der Valtimo-Wertauflöser (case:, doc: oder pv:).',
            'journaalpost.categorie': 'Kategorie',
            'journaalpost.categorie.tooltip': 'Dies kann ein fester Wert sein, aber auch einer der Valtimo-Wertauflöser (case:, doc: oder pv:).',
            'journaalpost.saldoSoort': 'Saldoart',
            'journaalpost.saldoSoort.tooltip': 'Wählen Sie den Saldentyp',
            'journaalpost.saldoSoort.placeholder': 'Bitte wählen',
            'journaalpost.omschrijving': 'Beschreibung',
            'journaalpost.omschrijving.tooltip': 'Dies kann ein fester Wert sein, aber auch einer der Valtimo-Wertauflöser (case:, doc: oder pv:).',
            'journaalpost.boekjaar': 'Buchungsjahr',
            'journaalpost.boekjaar.tooltip': 'Dies kann ein fester Wert sein, aber auch einer der Valtimo-Wertauflöser (case:, doc: oder pv:).',
            'journaalpost.boekperiode': 'Buchungsperiode',
            'journaalpost.boekperiode.tooltip': 'Dies kann ein fester Wert sein, aber auch einer der Valtimo-Wertauflöser (case:, doc: oder pv:).',
            'journaalpost.regels': 'Regeln',
            'journaalpost.regels.tooltip': 'Fügen Sie mindestens eine Journaleintragszeile hinzu.',
            'journaalpost.regel.toevoegen': 'Regel hinzufügen',
            'journaalpost.regel.verwijderen': 'Regel entfernen',
            'journaalpost.regel.grootboekSleutel': 'Hauptbuchschlüssel',
            'journaalpost.regel.boekingType': 'Buchungstyp',
            'journaalpost.regel.boekingType.placeholder': 'Bitte wählen',
            'journaalpost.regel.omschrijving': 'Beschreibung',
            'journaalpost.regel.bedrag': 'Betrag',
            'verkoopfactuur.procesCode': 'Prozesscode',
            'verkoopfactuur.procesCode.tooltip': 'Dies kann ein fester Wert sein, aber auch einer der Valtimo-Wertauflöser (case:, doc: oder pv:).',
            'verkoopfactuur.referentieNummer': 'Referenznummer',
            'verkoopfactuur.referentieNummer.tooltip': 'Dies kann ein fester Wert sein, aber auch einer der Valtimo-Wertauflöser (case:, doc: oder pv:).',
            'verkoopfactuur.factuurKlasse': 'Rechnungsklasse',
            'verkoopfactuur.factuurKlasse.tooltip': 'Wählen Sie die Rechnungsklasse aus',
            'verkoopfactuur.factuurKlassePlaceholder': 'Bitte wählen',
            'verkoopfactuur.inkoopOrderReferentie': 'Bestellreferenz',
            'verkoopfactuur.inkoopOrderReferentie.tooltip': 'Dies kann ein fester Wert sein, aber auch einer der Valtimo-Wertauflöser (case:, doc: oder pv:).',
            'verkoopfactuur.natuurlijkPersoonAchternaam': 'Nachname',
            'verkoopfactuur.natuurlijkPersoonAchternaam.tooltip': 'Dies kann ein fester Wert sein, aber auch einer der Valtimo-Wertauflöser (case:, doc: oder pv:).',
            'verkoopfactuur.natuurlijkPersoonVoornamen': 'Vornamen',
            'verkoopfactuur.natuurlijkPersoonVoornamen.tooltip': 'Dies kann ein fester Wert sein, aber auch einer der Valtimo-Wertauflöser (case:, doc: oder pv:).',
            'verkoopfactuur.nietNatuurlijkPersoonStatutaireNaam': 'Gesetzlicher Name',
            'verkoopfactuur.nietNatuurlijkPersoonStatutaireNaam.tooltip': 'Dies kann ein fester Wert sein, aber auch einer der Valtimo-Wertauflöser (case:, doc: oder pv:).',
            'verkoopfactuur.regels': 'Regeln',
            'verkoopfactuur.regels.tooltip': 'Fügen Sie mindestens 1 Rechnungszeile hinzu.',
            'verkoopfactuur.regel.toevoegen': 'Regel hinzufügen',
            'verkoopfactuur.regel.verwijderen': 'Regel entfernen',
            'verkoopfactuur.regel.hoeveelheid': 'Menge',
            'verkoopfactuur.regel.tarief': 'Tarif',
            'verkoopfactuur.regel.btwPercentage': 'MwSt.-Prozentsatz',
            'verkoopfactuur.regel.grootboekSleutel': 'Hauptbuchschlüssel',
            'verkoopfactuur.regel.omschrijving': 'Beschreibung'
        },
    },
};

export {rotterdamOracleEbsPluginSpecification};
